@startmindmap 31701KE1

title 31701 KE1 Personalführung
center footer https://github.com/fahrbier/fernuni/blob/main/31701-PF/KE1-mindmap.puml

+ Führung und Führungsbeziehungen\nBegriff, Charakterisierung und Entstehung
-- Grundlagen
---_ Objekte der Führung
----_ Einzelne Personen 
-----_ Eltern-Kinder
-----_ Lehrer-Schüler
-----_ Mitarbeiter

----_ Personengruppen 
-----_ Sportteam
-----_ Jugendbanden
-----_ Arbeitsgruppe
-----_ Abteilung\n(einer Organisation)

----_ Soziale Gebilde
-----_ Organisationen
-----_ Institutionen
-----_ Nationen

---_ Felder der Führung
----_ Wirtschaft
----_ Politik
----_ Militär
----_ Sport
----_ Familie 

--- Begründungsversuche
----_ Evolutionstheoretisch\nVorteil\nEntscheidungsprobleme zum...
-----_ ...überleben, finden+verteilen
-----_ ...verstehen Weltzusammenhang
-----_ ...umgang mit Macht
-----_ Zwei Muster
------_ antropologisch\n(Lehre vom Menschen)
------_ funktional




----_ Ideologisch

--- Menschenbilder
----_ nach McGregor
-----_ Theory X
-----_ Theory Y 

----_ nach Schein 
-----_ Rational-Economic 
-----_ Social 
-----_ Self Actualing
-----_ Complex

----_ Weinert&Langer  
-----_ Umfrage
------_ Passivität/Unselbstständig 
------_ Aktivität/Eigenverantwortung
------_ Komplex/individuelle Unterschiede
------_ Soziale Motive
------_ Anerkennung 
------_ Materielle Ziele/Status
------_ Limitierte Rationalität/Entscheiden
------_ Unbewusste Motive

-----_ Clusteranalyse aus Umfrage
------_ unprofiliert 
------_ tendenziell negativ
------_ realistisch positiv
------_ sowohl als auch
------_ idealistisch


--- Führungsverständnis
----_ als Persönlichkeit des Führers
----_ als Mittelpunkt des Gruppenprozesses
----_ als Sinngebung
----_ als Ausübung von Einfluss
----_ als zweidimienstionales Verhalten
-----_ Aufgabenorientierung
-----_ Beziehungsorientierung
----_ als Form der Überredung
----_ als Machtbeziehung
----_ als Ergebnis sozialer Interaktionale
----_ als Zuschreibung
----_ als Intrument der Zielerreichung
----_ als Rollendifferenzierung
----_ als Prozess

--- Führungsdefinition
----_ Auffassung
-----_ formal, Einflussausübung
-----_ interaktiv, Prozess
-----_ Richtung, Leistung/Zufriedenheit
-----_ Ziel, Leidenschaft erzeugen
-----_ Einflussversuch
----_ Kriterien
-----_ Verhaltensbeeinflussung
------_ Können
------_ Wollen
------_ soziales Dürfen und Sollen
------_ situative Ermöglichung
-----_ Akzeptanz
------_ Bereitschaft/Wahrnehmung\nEinflussversuch
-------_ Social Information Processing Theory
-------_ Reaktanztheorie
------_ Informationsassymetrie
------_ Zuschreibung Führer/Führung
------_ Leitung vs. Führung



-----_ Intentionalität
-----_ Unmittelbarkeit








-- Charakterisierung
--- Grundelemente
---- Dyade
-----_ 2 Personen interagieren
-----_ in einer Führungssituation
-----_ in einem Führungskontext
----_ Personale 
----_ Interaktionale 
----_ Situationale 

--- Wirksamkeit
----_ Ebenen des Führungserfolgs
-----_ Organisationsebene
------_ schwacher Einfluss
------_ deutlicher Einfluss
------_ -> heterogene Befundlage
------_ romantisierung 

-----_ Individuum / Gruppe
------_ Loyalität
------_ Motivation
------_ Zufriedenheit
------_ Konfliktneigung
------_ Kooperationsbereitschaft
------_ Qualität
------_ Kosten
------_ Moral

----_ Eigenschaften des Führungserfolgs
-----_ zuverlässig und objektiv 
-----_ zeitlich stabil 
-----_ umfassend und relevant
-----_ eindeutig und unabhängig 
-----_ differenzierend 

----_ übergeordnete Kriterien
-----_ Effizienz
------_ nach Wunderer
-------_ ökonomische Effizienz
-------_ soziale Effizienz

------_ nach Witte
-------_ generelle ökonomische Effizienz
-------_ Leistungsprozesseffizienz
-------_ Personeneffizienz


-----_ Effektivität
------_ Leistung
------_ Kohäsion
------_ Zufriedenheit



++ Entstehung
+++ Einzelperspektive
+++ Gruppenperspektive

@endmindmap