@startmindmap
title 31701 KE1 Personalführung
center footer https://github.com/fahrbier/fernuni/blob/main/31701-PF/KE1-mindmap.puml

+Führung und Führungsbeziehungen\nBegriff, Charakterisierung und Entstehung

@endmindmap
