@startmindmap
title 31701 KE2 Personalführung
center footer https://github.com/fahrbier/fernuni/blob/main/31701-PF/KE2-mindmap.puml

+ Ausrichtung von Führungsbeziehungen

-- Organisationen
--- Verhaltensbeeinflussung
----_ durch Organisation
----_ durch Personalführung

--- Badarf Personalführung 
----_ Org. weiss zu wenig um alle Konsequenzen zu bestimmen
----_ Org. kann nicht auf alles vorbereitet sein 
----_ Org. kennen Positionen aber nicht die Leute darauf
----_ Leistungsschwankunden der MA 
----_ Soziale Gebilde (Spannungen, Konflikte) 

--- Formen der soz. Kontrolle 
----_ vor-organisationale soziale Kontrolle
-----_ Elternahus
-----_ Sozialisation
-----_ Allgemein und Berufsbildung
----_ organisationale Potentialkontrolle 
-----_ Personalauswahl
-----_ Personalallokation
-----_ Qualifizierung
----_ organisationale Handlungskontrolle 
-----_ persönlich
------_ Vorgesetzte
------_ Kollegen, Unterstellte
-----_ unpersönlich
------_ Technik
------_ Anreizsysteme
------_ Stellenschneidung

--- Aktive Führungsanstrengunen
----_ int. und ext. Org.geschehen interpretieren
----_ MA motivieren
----_ Fähigkeiten entwickeln
----_ Ziele verdeutlichen
----_ Belohnung in Aussicht stellen
----_ individuelle Bedürfnisse erkennen
----_ Vertrauen schaffen

--- Personalführung\nvs. Organisation
---- Verhältnis
-----_ Org. bietet strukturierten Raum für Führung
-----_ Org. ist erklärungsbedürftig
-----_ Org. ist umsetzungsbedürftig


----_ Entpersonalisierte
----_ Substitute

++ Motivation

+++ Inhaltsanalytisch

+++ Prozessanalytisch

+++ Funktionsanalytisch


@endmindmap
