@startmindmap
title 31701 KE2 Personalführung
center footer https://github.com/fahrbier/fernuni/blob/main/31701-PF/KE2-mindmap.puml

+ Ausrichtung von Führungsbeziehungen

-- Organisationen
--- Verhaltensbeeinflussung
----_ durch Organisation
----_ durch Personalführung

--- Badarf

--- Personalführung\nvs. Organisation
----_ Entpersonalisierte
----_ Substitute

++ Motivation

+++ Inhaltsanalytisch

+++ Prozessanalytisch

+++ Funktionsanalytisch


@endmindmap
