@startmindmap
title 32641 KE1 Internationales Management
center footer https://github.com/fahrbier/fernuni/blob/main/32641-IM/KE1-mindmap.puml

+ Internationales\nManagement
++ Kulturforschung
+++ Hofstede 
++++_ Machtdistanz
++++_ Unsicherheitsvermeidung
++++_ Individualismus\nKollektivismus
++++_ Maskulinität\nFenminität
++++_ Konfuzianische\nDynamik
++++_ Genussorientierung\nZurückhaltung
+++ GLOBE
++++_ Unsicherheitsvermeidung
++++_ Machtdistanz
++++_ Kollektivismus 1
++++_ Kollektivismus 2
++++_ Geschlechtergleichheit
++++_ Bestimmtheit
++++_ Zukunftsorientierung
++++_ Leistungsorientierung
++++_ Humanorientierung
++ Organisationen
+++ International
++++_ Staatlich
+++++_ ILO 
+++++_ IWF 
+++++_ IBRD 
+++++_ WTO 
++++++_ GATT 
++++++_ GATS  
++++++_ TRIPS 
+++++_ OECD  
++++++_ Stabilität 
++++++_ Wachstum 
++++++_ Ausweitung 
++++_ Nichtstaatlich
+++++_ Greenpeace
+++++_ Fridays For Future 
+++ Regional Staatlich
++++_ EU 
++++_ NAFTA 
++++_ CAPRICOM 
++++_ MERCOSUR
++++_ ASEAN 
++++_ APEC
+++ Verhaltenskodizes 
++++_ sachlich 
+++++_ universell
+++++_ speziell

++++_ geografisch 
+++++_ weltweit
+++++_ regional
+++++_ länderspezifisch

++++_ institutionell
+++++_ staatlich 
+++++_ nichtstaatlich


-- Grundlegendes
--- Ziele 
----_ individuell (Motiv)
----_ unternehmensbezogen 
-----_ absatzmarktorientiert
-----_ kosten-/ertragsorientiert
-----_ beschaffungsorientiert
--- National vs. International 
----_ Orientierung EPRG
-----_ ethno
-----_ poly
-----_ geo
-----_ regio
----_ Unternehmenstyp
-----_ multi 
-----_ global
-----_ International
-----_ transnational
--- Dimensionen
----_ quantitativ/qualititiv\nInternationalisierungsgebirge
-----_ Integration
-----_ Wertschöpfung
-----_ Geo-kulturelle Distanz
--- Funktionen Management
----_ funktionale Sicht 
-----_ planen (planning)
-----_ organisieren (organizing)
-----_ personalbeschaffen (staffing) 
-----_ führen  (directing)
-----_ kontrollieren (controlling)
----_ insitutionelle Sicht 
-----_ Positionen mit\nWeisungsbefugnis
--- Problemfelder
----_ neue Umwelt
----_ länderspez. Dynamik
----_ erhöhte Komplexität
-- Theorien
--- Internationale\nUnternehmertätigkeit
----_ Aussenhandelstheorie
-----_ klassisch
-----_ neoklassisch
----_ Direktinvestition
-----_ Monopolistischer\nWettbewerbsvorteil
-----_ Internalisierungstheorie
-----_ Standorttheorie 
----_ Technologieverträge
----_ Eklektische Theorien
--- Internationalisierung\nProzess 
----_ Zeitliche Dimension\nDirektinvestition 
-----_ Produktlebenszyklus
-----_ Oligopolistisches Parallelverhalten
-----_ Verhaltenswissenschaft
-----_ Evolutionär, wissensbasiert
----_ Behavioristisch 
-----_ Uppsala
-----_ Netzwerkgedanke
-----_ Helsinki
----_ GAINS 
--- Diamantmodell Porter 
----_ Bestimmungsfaktor
-----_ Faktorbedingung
-----_ Nachfragebedingung
-----_ verwandte/unterst.Branche
-----_ Unternehmensstrategie,\nStruktur und Wettbewerb
----_ ergänzender Faktor 
-----_ Zufall
-----_ Staat 
--- Strategische Ansätze 
----_ Kontingenztheoretisch
-----_ Machtpositionsmatrix
------_ Vielfältigkeit/Komplexität\nUnternehmensumwelt
------_ Intraorganisatorische\nVerknüpfungen
-----_ Unification-Fragmentation-\nFramework
-----_ Globalisierungsansatz Porter
------_ Konfiguration
------_ Koordination

----_ Ressourcen-\nund kompetenzorientiert
-----_ transnationale Wettbewerbsfähigkeit
------_ Unternehmen\nals Netzwerk
------_ Kein internes\nRessourcenmonopol
------_ Faktorkosten versch.\nMärkte nutzbar
-----_ Management-\nqualitätsansatz
------_ strukturelle Unbestimmtheit
------_ interne Differenzierung
------_ integrative Optimierung
------_ Intensität des Informationsaustauschs
------_ Latente Verbindungen
------_ Netzwerkorganisation
------_ Lernprozess und Kontinuität
-----_ Heterarschisches\n   Management
------_ Viele Zentren im Unternehmen
------_ Auch Auslandsges.\nstrategisch bedeutend
------_ Integration nach Normativem
------_ Offen für Verbindungen\nzu andere UN
------_ Problemorientiert
------_ Wissen bewahren
------_ nicht zentral gesteuerte\nintellektuelle Einheit
@endmindmap
