@startmindmap
title 32641 KE1 Internationales Management

+ Internationales\nManagement
++ Kulturforschung
+++ Hofstede 
++++_ Machtdistanz
++++_ Unsicherheitsvermeidung
++++_ Individualismus\nKollektivismus
++++_ Maskulinität\nFenminität
++++_ Konfuzianische\nDynamik
++++_ Genussorientierung\nZurückhaltung
+++ GLOBE
++++_ Unsicherheitsvermeidung
++++_ Machtdistanz
++++_ Kollektivismus 1
++++_ Kollektivismus 2
++++_ Geschlechtergleichheit
++++_ Bestimmtheit
++++_ Zukunftsorientierung
++++_ Leistungsorientierung
++++_ Humanorientierung
++ Internationale\nOrganisatiosnen
+++ International
++++_ Staatlich
+++++_ ILO 
+++++_ IWF 
+++++_ IBRD 
+++++_ WTO 
++++++_ GATT 
++++++_ GATS  
++++++_ TRIPS 
+++++_ OECD  
++++++_ Stabilität 
++++++_ Wachstum 
++++++_ Ausweitung 
++++_ Nichtstaatlich
+++++_ Greenpeace
+++++_ Fridays For Future 
+++ Regional Staatlich
++++_ EU 
++++_ NAFTA 
++++_ CAPRICOM 
++++_ MERCOSUR
++++_ ASEAN 
++++_ APEC
+++ Verhaltenskodizes 
++++_ sachlich 
+++++_ universell
+++++_ speziell

++++_ geografisch 
+++++_ weltweit
+++++_ regional
+++++_ länderspezifisch

++++_ institutionell
+++++_ staatlich 
+++++_ nichtstaatlich


-- Grundlegendes
--- Ziele 
----_ individuell (Motiv)
----_ unternehmensbezogen 
-----_ absatzmarktorientiert
-----_ kosten-/ertragsorientiert
-----_ beschaffungsorientiert
--- National vs. International 
----_ Orientierung EPRG
-----_ ethno
-----_ poly
-----_ geo
-----_ regio
----_ Unternehmenstyp
-----_ multi 
-----_ global
-----_ International
-----_ transnational
--- Dimensionen
----_ quantitativ/qualititiv\nInternationalisierungsgebirge
-----_ Integration
-----_ Wertschöpfung
-----_ Geo-kulturelle Distanz
--- Funktionen Management
----_ funktionale Sicht 
-----_ planunen (planning)
-----_ organisieren (organizing)
-----_ personalbeschaffen (staffing) 
-----_ führen  (directing)
-----_ kontrollieren (controlling)
----_ insitutionelle Sicht 
-----_ Positionen mit\nWeisungsbefugnis
--- Problemfelder
----_ neue Umwelt
----_ länderspez.nDynamik
----_ erhöhte Komplexität
-- Theorien
--- Internationale\nUnternehmertätigkeit
----_ Aussenhandelstheorie
-----_ klassisch
-----_ neoklassisch
----_ Direktinvestition
-----_ Monopolistischer\nWettbewerbsvorteil
-----_ Internalisierungstheorie
-----_ Standorttheorie 
----_ Technologieverträge
----_ Eklektische Theorien
--- Internationalisierung\nProzess 
----_ Zeitliche Dimension\nDirektinvestition 
-----_ Produktlebenszyklus
-----_ Oligopolistisches Parallelverhalten
-----_ Verhaltenswissenschaft
-----_ Evolutionär, wissensbasiert
----_ Behavioristisch 
-----_ Uppsala
-----_ Netzwerkgedanke
-----_ Helsinki
----_ GAINS 
--- Diamantmodell Porter 
--- Strategische Ansätze 
----_ Kontingenztheoretisch
----_ Ressourcen- und kompetenzorientiert

@endmindmap
