@startmindmap
title 32641 KE2 Internationales Management
center footer https://github.com/fahrbier/fernuni/blob/main/32641-IM/KE2-mindmap.puml

+ IM KE2
-- Planung 
--- Grundlagen
----_ gedankliche Vorwegnahme\nzuk.Handelns
----_ Zielplanung
----_ Massnahmenplanung
----_ stategisch: mehr\nErfolgspotentiale finden
----_ operativ: bestehende\nErfolgspotentiale nutzen


--- strategische\nAnalyse
----_ Umwelt
-----_ Chancen 
-----_ Risiken
----_ Unternehmen
-----_ Stärken 
-----_ Schwächen
---- Umweltanalyse
-----_ globale
------_ horizontal
-------_ Interaktionspartner
-------_ deren Beziehung
------_ vertikal
-------_ natürliche Umwelt
-------_ kulturelle Umwelt\n(man made)
-----_ Wettbewerbsumwelt

------_ Stakeholder
-------_ verfolgt Ziel
-------_ hat Macht 
-------_ hat Legitimität
-------_ hat Dringlichkeit
-------_ birgt Risiko
-------_ potentielle
-------_ koalieren 
--------_ Mitarbeiter
--------_ Gewerkschaft
--------_ Kapitalgeber
--------_ Lieferanten
--------_ Abnehmer/Kunden
--------_ Konkurrenten
--------_ Staat
------_ Wettbewerb
-------_ Ländermarktbarrieren
--------_ Unkenntnis über\nLand, Konsument, Lieferat
--------_ kulturelle Distanz
--------_ Wechselkurs
-------_ Verhaltensweisen
--------_ FollowUp
--------_ Follow the Leader
--------_ Cross Investment
-------_ Weltmarkt
--------_ Volumen
--------_ Potential
--------_ Konkurrenten
-------_ strategische Gruppen
-------_ Konkurrenten


-----_ Markt & Standort
------_ Vorauswahl
-------_ sachliche Gründe
-------_ werthaltige Gründe
-------_ strategische Gründe
-------_ faustregelartige Gründe

------_ Grobanalyse
-------_ Ländermärkte
--------_ Ertragschancen
--------_ Marktvolumen
--------_ Marktwachstum
--------_ Abnehmerstruktur
-------_ Markteintrittsbarrieren
--------_ Zölle
--------_ Verbraucherschutz
--------_ Local-Content
--------_ Gründungsverbot Ausl.
--------_ Präferenzen Lieferanten
--------_ Ressourcenausstattung
--------_ kulturelle Distanz
-------_ Länderrisiken
--------_ politische Risiken
--------_ wirtschaftl. Risiken 
-------- Einschätzung mithilfe\nvon Sekundärquellen\n Beispiel BRS 
---------_ Operations Risk Index 
---------_ Political Risk Index 
---------_ R(ückzahlungs)-Faktor 



------_ Feinanalyse
-------_ Marktsegmentierung
-------_ Standortwahl

---- Unternehmensanalyse
---- Entscheidungskompetenzen\nzentral/dezentral
---- Global/Standard\nLokal/Differenziert
---- Eintrittsformen
---- Zeitaspekt
---- Konfiguration
---- Ressourcen&Kompetenzen

++ Organisation 
+++ Grundlagen
++++_ UN ist Orga
++++_ UN hat Orga
+++++_ Arbeitsteilung
+++++_ Koordination
+++++_ Fremdorganisation\n(hierarchich)
+++++_ Selbstorganisation\n(horizontal)
+++++_ Struktur
++++++_ statutarisch\nde jure
++++++_ operational\nde facto
+++++++_ funktional\nnach Aufgaben
++++++++_ F&E
++++++++_ Beschaffung
++++++++_ Produktion
++++++++_ Absatz
+++++++_ divisional\nnach Objekten
++++++++_ Produkte
++++++++_ Region
++++++++_ Kunden
+++++_ Auslandsgeschäft
++++++_ integriert
++++++_ differenziert

+++ Differenzierte Strukturen
++++_ Inlandsgeschäft
++++_ Auslandsgeschäft\nInternational Division
+++++_ + konzentration auf Auslandsaktivität
+++++_ + Minimal Kommunikationswege
+++++_ + Spezialisierungsvorteile
+++++_ + klare Trennung, kein Kompetenzstreit
+++++_ - Isolierungstendenzen
+++++_ - hohe Abhängigkeit von Nationalen
+++++_ - suboptimale Nutzung Wachstumschancen
+++++_ - Konkurrenzdenken/Rivalitäten




+++ Integrierte Strukturen
++++_ Funktionalstruktur
+++++_ + Spezialisierung
+++++_ + funktionsinterne Synergieen
+++++_ + unkomplizierte integr. intern. Aktivität
+++++_ - bei Internationalisierung im grossen Maß, große Belastung
+++++_ - zunehmende Diverstifikation, mehr Koordination
+++++_ - kommt zu hoher und zeitintensiver Kommunikation
+++++_ - Flexibilität und Effizienz können abnehmen
++++_ Produktstruktur
+++++_ + Vorteil
+++++_ - Nachteil
++++_ Regionalstruktur
+++++_ + Vorteil
+++++_ - Nachteil
++++_ Mehrdimensionale Strukturen
+++++_ + Vorteil
+++++_ - Nachteil

+++ Holdingstruktur

+++ Projektorganisation

+++ Einflussfaktoren Strukturwahl\nempirische Befunde

@endmindmap
