@startmindmap
title 32641 KE2 Internationales Management
center footer https://github.com/fahrbier/fernuni/blob/main/32641-IM/KE2-mindmap.puml

+ IM KE2
-- Planung 
--- Grundlagen
----_ gedankliche Vorwegnahme\nzuk.Handelns
----_ Zielplanung
----_ Massnahmenplanung
----_ stategisch: mehr\nErfolgspotentiale finden
----_ operativ: bestehende\nErfolgspotentiale nutzen


--- strategische\nAnalyse
----_ Umwelt
-----_ Chancen 
-----_ Risiken
----_ Unternehmen
-----_ Stärken 
-----_ Schwächen
---- Umweltanalyse
-----_ globale
------_ horizontal
-------_ Interaktionspartner
-------_ deren Beziehung
------_ vertikal
-------_ natürliche Umwelt
-------_ kulturelle Umwelt\n(man made)
-----_ Wettbewerbsumwelt

------_ Stakeholder
-------_ verfolgt Ziel
-------_ hat Macht 
-------_ hat Legitimität
-------_ hat Dringlichkeit
-------_ birgt Risiko
-------_ potentielle
-------_ koalieren 
--------_ Mitarbeiter
--------_ Gewerkschaft
--------_ Kapitalgeber
--------_ Lieferanten
--------_ Abnehmer/Kunden
--------_ Konkurrenten
--------_ Staat
------_ Wettbewerb
-------_ Ländermarktbarrieren
--------_ Unkenntnis über\nLand, Konsument, Lieferat
--------_ kulturelle Distanz
--------_ Wechselkurs
-------_ Verhaltensweisen
--------_ FollowUp
--------_ Follow the Leader
--------_ Cross Investment
-------_ Weltmarkt
--------_ Volumen
--------_ Potential
--------_ Konkurrenten
-------_ strategische Gruppen
-------_ Konkurrenten


-----_ Markt & Standort
------_ Vorauswahl
-------_ sachliche Gründe
-------_ werthaltige Gründe
-------_ strategische Gründe
-------_ faustregelartige Gründe

------_ Grobanalyse
-------_ Ländermärkte
--------_ Ertragschancen
--------_ Marktvolumen
--------_ Marktwachstum
--------_ Abnehmerstruktur
-------_ Markteintrittsbarrieren
--------_ Zölle
--------_ Verbraucherschutz
--------_ Local-Content
--------_ Gründungsverbot Ausl.
--------_ Präferenzen Lieferanten
--------_ Ressourcenausstattung
--------_ kulturelle Distanz
-------_ Länderrisiken
--------_ politische Risiken
--------_ wirtschaftl. Risiken 
-------- Einschätzung mithilfe\nvon Sekundärquellen\n Beispiel BRS 
---------_ Operations Risk Index 
---------_ Political Risk Index 
---------_ R(ückzahlungs)-Faktor 



------_ Feinanalyse
-------_ Marktsegmentierung
-------_ Standortwahl

---- Unternehmensanalyse
-----_ Funktionsbereichsanalyse
------_ Ressourcen
-------_ finanziell
-------_ physisch
-------_ personell
-------_ organisatorisch
-------_ technologisch
------_ Probleme
-------_ inderdependenzen werden ausgeblendet
-------_ immaterielles (z.B. Wissen) nicht im Blick
-------_ grössere UN eher objektorientiert als funktnl.

-----_ Wertkettenanalyse
------_ primäre
-------_ Logistik
-------_ Produktion
-------_ Marketing
-------_ Vertrieb
-------_ Kundendienst
------_ unterstützende
-------_ Beschaffung
-------_ F&E
-------_ Personal
-------_ Führungs- & Informationssystem
------_ horizontal\nzwischen Geschäftsfeldern
------_ vertikal\nmit Liefereanten und Abnehmern
------_ bei Lösung von Kundenproblemen\nWertkette nicht sequentiell sod. zylisch\nVALUE SHOP

-----_ Ressource Based View
------_ materielle
------_ finanzielle
------_ personelle
------_ immaterielle 
-------_ Wissen
-------_ Reputation
-------_ Marken
-------_ Patente
------_ dynamische Kompetenzen
------_ VRIO bewertet Ress.&Komp. 
-------_ Wettbewerbsvergleich
-------_ Benchmarking

---- Strategiedimensionen 
-----_ Orientierung
------_ ethno
-------_ Komplexität: Stammhaus
-------_ Entscheidungen: Stammhaus
-------_ Kontrolle: Stammhaus
-------_ Sanktionen: Stammhaus
-------_ Kommunikation: Stammhaus > Tochter
-------_ Identifikation: Stammland
-------_ Führungpositionen: aus Stammhaus


------_ poly
-------_ Komplexität: verschieden, keine Abhängikeit
-------_ Entscheidungen: dezentral
-------_ Kontrolle: lokale Bestimmungen
-------_ Sanktionen: Töchter nach versch. Kriterien
-------_ Kommunikation: gering
-------_ Identifikation: Gastland
-------_ Führungpositionen: MA Gastland


------_ regio
-------_ Komplexität: hohe gegens.regionale Abh.
-------_ Entscheidungen: regionales HQ
-------_ Kontrolle: regionale Bestimmungen
-------_ Sanktionen: nach reg. Zielvorgaben
-------_ Kommunikation: gering Mutter, hoch reg.HQ.
-------_ Identifikation: Regional
-------_ Führungpositionen: MA Region

------_ geo
-------_ Komplexität: hohe weltw. Abh.
-------_ Entscheidungen: weltw. Zusammenarb.
-------_ Kontrolle: universale und lokale
-------_ Sanktionen: nach Zielvorgaben
-------_ Kommunikation: hoch & reziprok
-------_ Identifikation: Weltw. Unternehmen, wahrung nat. Interessen
-------_ Führungpositionen: nur nach Qualifikation

-----_ Dimensionen

------_ Zentral-/Dezentralisierung
-------_ etno vs. geo
--------_ Zentral allenfalls am Anfang
--------_ Dezntral bei geo,\nes soll zusammen-\ngearbeitet werden
-------_ poly vs. regio
--------_ heterarschiches Konzept
--------_ schnelle lokale Anpassung
--------_ poly erschwert Arbitrage,\nLeverage, Verbund...
--------_ regio schafft Unterzentren\num Arbitrage, Leverage, etc.\n zu ermöglichen.



------_ Differenzierung/Standardisierung
-------_ pro Standardisierung
--------_ ISO
--------_ sinkende Transp.kosten
--------_ kurze Prod.lebens.zkl.
--------_ Konvergenzthese
--------_ Standardisierungsthese
--------_ Zentralisierungsthese
--------_ Preisvorteilsthese
-------_ pro Differenzierung
--------_ Local Content Vorschr.
--------_ divergierende Anforderungen
--------_ Markteintrittsbarrieren
--------_ Haltbarkeit b. Lebensmitteln.

-------_ Empfehlungen\nnach Vorteil
--------_ wenig Global, wenig Lokal\nINTERNATIONAL
--------_ wenig Global, viel Lokal\nMULTINATIONAL
--------_ viel Global, wenig Lokal\nGLOBAL
--------_ viel Global, viel Lokal\nTRANSNATIONAL



------_ Eintrittsformen
-------_ Begrenzungsfaktoren
--------_ UN-intern
---------_ UN politische Normen
---------_ Internationalisierungsphilosophie
---------_ Technologie
---------_ Kapazitätsauslastung
--------_ UN-extern
---------_ Zölle
---------_ Steuern
---------_ Import/Exportquoten
---------_ Wechselkurse
---------_ Devisen-/Ka[italmarktbeschränkungen

-------_ Vorteilhaftigkeit
--------_ UN-extern
---------_ landespez.Risiko
---------_ politisches Risiko
---------_ ökonomisches Risiko
---------_ kulturelles Risiko
---------_ soziales Risiko
---------_ Naturereignisse

--------_ UN-intern
---------_ Ressourcenausstattung
---------_ Sdt/Diff
---------_ Entschd.zentralisation
---------_ Wertschöpfung
---------_ Managementerfahrung
---------_ Sprache, Kultur, ...




-------_ Vertretung durch Dritte
--------_ (indirekter) Export
---------_ sehr geringe Ressourcenbindung
---------_ sehr geringe Steuerrungsmgl.
---------_ bei indir. mit lokale Vertriebspartnern
--------_ Lizenz
---------_ geringe Ressourcenbindung
---------_ geringe Steuerrungsmgl.
--------_ Franchise
---------_ geringe Ressourcenbindung
---------_ höhere Steuerrungsmgl.


-------_ Kooperation
--------_ Managementvertrag
---------_ KnowHow gegen Vergütung
---------_ riskoarm 
---------_ ländersp. know how 
---------_ befristet Verträge 

--------_ Vertragsfertigung
---------_ Teil, End oder Komplettfertigung
---------_ umgehung von Handelshemmnis 
---------_ geringeres Risiko als DI 
---------_ Problem wenn Termin/Qualitaet nOK 


--------_ Kooperation i.e.s. 
---------_ >2 UN vertraglich gebunden
---------_ all UN rechtlich selbstaendig
---------_ auch "Strategische Allianz" 

--------_ Netzwerkeintritt
---------_ mehrere UN treten gleichzeitig in  Markt 
---------_ Eintritt in unreife Märkte 

--------_ Joint Venture
---------_ Zusammenarbeit auf Dauer 
---------_ mit Kapitalbeteiligung 
---------_ ein jur. selbsts. UN
---------_ Gewinn&Risiko teilen

-------_ Tochtergesellschaft
--------_ hohe Ressourcenbindung, volle Kontrolle

--------_ Neugründung
--------_ Akquisition
--------_ Form
---------_ Verkaufsniederlassung
---------_ Produktion/Montage
---------_ Vollintegr. Tochter
--------_ virtueller Markteintritt 
---------_ wenig Investition, hohe Kontrolle
---------_ Auslieferung mit Partnern

------_ Zeitaspekt
-------_ länderübergreifend
--------_ Sprinkler
--------_ Wasserfall
-------_ länderspezifisch
--------_ Pionier
--------_ Folger


------_ Konfiguration
-------_ Wertschöpfungskette
-------_ Konzentration vs. Streuung
-------_ Kontrolle
-------_ Autonomie vs. straffe Koordination
-------_ Tendezaussagen
--------_ Logistik, Marketing, Vertrieb in Kundennähe
--------_ int. Logistik, operative Fkt. eher Konzentration
--------_ #Standorte abh. von Degressionseffekten
--------_ Kostenvorteile bestst. geographische Lage 
-------_ strategische Dimension
--------_ F&E - Kostenvorteile
--------_ Beschaffung - Streuung
--------_ Produktion - Local-Content-Vorschr.
--------_ Vertrieb - geringe Standardisierung 


------_ Ressourcen&Kompetenzen

++ Organisation 
+++ Grundlagen
++++_ UN ist Orga
++++_ UN hat Orga
+++++_ Arbeitsteilung
+++++_ Koordination
+++++_ Fremdorganisation\n(hierarchich)
+++++_ Selbstorganisation\n(horizontal)
+++++_ Struktur
++++++_ statutarisch\nde jure
++++++_ operational\nde facto
+++++++_ funktional\nnach Aufgaben
++++++++_ F&E
++++++++_ Beschaffung
++++++++_ Produktion
++++++++_ Absatz
+++++++_ divisional\nnach Objekten
++++++++_ Produkte
++++++++_ Region
++++++++_ Kunden
+++++_ Auslandsgeschäft
++++++_ integriert
++++++_ differenziert

+++ Differenzierte Strukturen
++++_ Inlandsgeschäft
++++_ Auslandsgeschäft\nInternational Division
+++++_ + konzentration auf Auslandsaktivität
+++++_ + Minimal Kommunikationswege
+++++_ + Spezialisierungsvorteile
+++++_ + klare Trennung, kein Kompetenzstreit
+++++_ - Isolierungstendenzen
+++++_ - hohe Abhängigkeit von Nationalen
+++++_ - suboptimale Nutzung Wachstumschancen
+++++_ - Konkurrenzdenken/Rivalitäten




+++ Integrierte Strukturen
++++_ Funktionalstruktur
+++++_ + Spezialisierung
+++++_ + funktionsinterne Synergieen
+++++_ + unkomplizierte integr. intern. Aktivität
+++++_ - bei Internationalisierung im grossen Maß, große Belastung
+++++_ - zunehmende Diverstifikation, mehr Koordination
+++++_ - kommt zu hoher und zeitintensiver Kommunikation
+++++_ - Flexibilität und Effizienz können abnehmen
++++_ Produktstruktur
+++++_ + Vorteil
+++++_ - Nachteil
++++_ Regionalstruktur
+++++_ + Vorteil
+++++_ - Nachteil
++++_ Mehrdimensionale Strukturen
+++++_ + Vorteil
+++++_ - Nachteil

+++ Holdingstruktur

+++ Projektorganisation

+++ Einflussfaktoren Strukturwahl\nempirische Befunde

@endmindmap