@startmindmap
title 32641 KE3 Internationales Management
center footer https://github.com/fahrbier/fernuni/blob/main/32641-IM/KE3-mindmap.puml

+ IM KE3
-- Personal
--- Grundlagen
----_ Personalpolitische Grundhaltung
-----_ enthno
-----_ poly
-----_ regio/geo
----_ Internationalisierungsmodelle
-----_ global
-----_ multinational
-----_ integrativ-situativ
-----_ international

--- Beschaffung
----_ Herkunft 
-----_ PCN Parent Country (Stammland)
-----_ HCN Host Country (Gastland)
-----_ TCN Third Country (Rest)

----_ interkulturelle Kompetenz
-----_ affektiv
-----_ kognitiv
-----_ verhaltensbezogen

--- Grenzüb.Einsatz
----_ Ziele
-----_ Wissenstransfer
-----_ Koordination/Kontrolle
-----_ Personalentwicklung

----_ Einfluss auf\nEntsendungs-\nbereitschaft
-----_ Kosten
-----_ Ziele
-----_ Funktion
-----_ Position
-----_ Dauer
-----_ Vorbereitung
-----_ Betreuung
-----_ Reintegration

--- Alternativen zur\ntrad. Entsendung
----_ Kurzzeitentsendung (<1J)
----_ (Mehr)wöchentliche Pendler
----_ Rotierende Assignments
-----_ Ölbohrinsel
-----_ Krisengebiet
----_ Vielflieger\nversch. Standorte\nnacheinander
-----_  Berater
-----_  Projektmanager
-----_  Repräsentation
----_ Virtueller Ausl.Einsatz

--- Phasen der Entsendung
----_ Auswahlphase
----_ Vorbereitung
----_ Einsatz
----_ Rückkehr

--- Mitbestimmung (TBD)

++ Controlling

+++ Funktionale Sicht\naufs Management
++++_ Entscheidungen Treffen
+++++_ Planung
+++++_ Organisation
+++++_ Personal
++++_ Informationen beschaffen
+++++_ Controlling
++++++_ Informationsbedarf
++++++_ Informationsbereitstellung

+++ Komplexitätsbehandlung
++++_ Selektion
+++++_ Planung
+++++_ Organisation
+++++_ Personal
++++_ Reflexion
+++++_ Controlling

+++ Rahmenbedingungen
++++_ Heterogene Umwelten\n->hohe Komplexitaet
++++_ interne
+++++_ Zieldivergenz
++++++_ Gesamtunternehmen
++++++_ nationale Ziele
+++++_ Ausgestaltung\ndiff. Controlling
++++++_ je nach Orientierung
++++++_ je nach Entsch.Zentralisa.
++++++_ je nach Standardisierung
+++++_ Länderengagement
++++++_ Export
++++++_ Tochter
++++++_ vollständige Werts.kette
++++++_ Lead-Country-Concept 
++++++_ ...
+++++_ Strategie
++++++_ Aufgabenverteilung
++++++_ Kompetenzverteilung
++++++_ Leistungsverpflechtung\n(Interdependenzen) 
++++++_ Info. & Kommunikationsbeziehungen



++++_ externe 
+++++_ neues Land, neue Umwelt hinzu
+++++_ ökonomische und rechtliche Rahmenbedingungen
+++++_ Wechselkurs
+++++_ Länderrisiken
+++++_ Kultur 
++++++_ Sprache
++++++_ Werte
++++++_ Normen
++++++_ Grundannahmen
+++++_ Kommunikationsschwierigkeiten
++++++_ Zugang zu Information
++++++_ Form 
++++++_ Häufigkeit
++++++_ Zeitpunkt
+++++_ räumliche Distanz



@endmindmap
