@startmindmap
title 32641 KE3 Internationales Management
center footer https://github.com/fahrbier/fernuni/blob/main/32641-IM/KE3-mindmap.puml

+ IM KE3
-- Personal
--- Grundlagen
----_ Ziele & Besonderheiten
----_ Intenationalisierungsmodelle
-----_ global
-----_ multinational
-----_ integrativ-situativ
-----_ international

@endmindmap
