@startmindmap 31102

skinparam defaultFontName Courier
title 31102 KE1 Theoretische Ansätze

 
+ Ansätze
-- Traditionell
---_ Scientific Management\nnach 🥼 Taylor
----_ 👉 Optimiert Fertigung

----_ 👍 Trennung Plan und Tun 
----_ 👍 Kontrolle
----_ 👍 differenzierte Akkortsätze 

----_ 👎 entfremdung des Menschen
----_ 👎 wachsende Widerstände


---_ administrativ
----_ 👉 Optimiert ganze Organisation


----_ 👉 Mgm.Funktionen nach 🥼 Fayol
-----_ Planung
-----_ Organisation
-----_ Befehl
-----_ Koordination
-----_ Kontrolle 
----_ 👉 Management Process School nach Koontz/O'Donnell

----_ 👉 Typen der Herrschaft nach 🥼 Weber
-----_ 👉 keine nat. Strukturen,\neine rationale Ordnung
-----_ Bürokratie
------_ 👉 Arbeitsteilung
------_ 👉 Hierarchie






-- Verhalten
---_ Human Relations
----_ 👉 Abkehr vom Taylorismus
----_ 👉 Erkennisse aus Psychologie und Soziologie
----_ 👉 Beziehung Arbeiter zu Leitung betrachten
----_ 👉 Hawthorne Experimente


---_ UN als kooperatives System
----_ 👉 Brückenschlag trad. u. verhaltensw.
----_ 👉 organisatorische Balance
----_ 👉 neben hierarchichen auch informelle Beziehungen
----_ 👉 Anreize statt Sanktionen
----_ 👉 individuelle Ziele beachten


---_ begrenzte Rationalität
----_ 👉 Gruppenentscheidungen vs. Optimierungskalkül
----_ 👉 Man strebt "nur" zufriedenstellende Lösungen an
----_ 👉 Mensch nicht in der Lage Nutzen von Orga. zu maximieren.




-- Institutionen/Ökonomisch
---_ 👉 modifiziert neoklassische Annahmen
---_ Verfügungsrechte (VR) Theorie
----_ 🥼 Alchian/Demsetz
----_ Entstehung und Wandel von VR
----_ 🔎 Untersucht UN-Verfassung und Managerverhalten

---_ Transaktionskosten Theorie
----_ 🥼 Coase
----_ Nicht nur Produktionskosten
----_ Vorbereitungskosten
----_ Kontrollkosten
----_ 🔎 Untersucht vertikale Integration od. UN Kooperationen

---_ Agentur Theorie
----_ 🥼 Ebers/Gotsch
----_ Anreizsysteme
----_ Kontrollsysteme
----_ Informationssysteme
----_ 🔎 Untersucht Vergütungssysteme & Perfo. Measurement

++ Formalwissenschaftlich
+++_ mathematische Enscheidungsmodelle
+++_ Management Science
+++_ Operations Research
+++_ 👍 Planungsprobleme handhabbar (teilweise)


++ Systemtheoretisch
+++_ 🥼 Bertalanffy (Biologe)
+++_ 👉 kybernetische (=organisch-technische)\nMechanismen, 3 Stränge
+++_ 1️⃣ Allgemeine Systemtheorie (ST)
+++_ 2️⃣ Integration 
+++_ 3️⃣ soziologisch ausgerichtete ST
+++_ 🔎 Untersucht kybernetisches Gleichgewicht (2️⃣)
+++_ System-Umwelt-Beziehung.(3️⃣)  
++++_ offenes System
++++_ interaktiv
++++_ Systeme passen sich an Umwelt an 
++++_ und Systeme gestalten Umwelt aktiv mit 
++++_ Kommunikation als Element zur\nReproduktion und Bestandssicherung
++++_ 👉 Autopoiesis, Manager steuern nicht\nsondern intervenieren!




++ Evolutionär
+++_ 👉 Fit Unternehen und Umwelt
+++_ 🥼 Scherm/Julmi
+++_ Population-Ecology Ansatz
++++_ 🥼 Deeg
++++_ Organisatorischer Wandel\ndurch Auslese der Umwelt
++++_ Management stellt Variationen her 
++++_ Ähnliche Organisationen
+++++_ Phänotyp - auessere Gestalt
+++++_ Genotyp - vererbbare Information
++++_ Mechanismen Evolutionsprozess
+++++_ Variation (Innovation)
+++++_ Selektion (Live or Die)
+++++_ Retention (Documentation)




+++_ Schaffung günstiger Rahmenbedingungen
++++_ St. Galler Ansatz
+++++_ 🥼 Hayek
+++++_ soziale Regeln nicht bewusst gesetzt
+++++_ UN Komplexitaet erzeugt Variationen
+++++_ Management ist Katalysator (Facilitator) 🥼 Probst 
+++++_ Management gibt keine detaillierten Anweisungen

++++_ Münchner Ansatz
+++++_ 🥼 Kirsch
+++++_ bewaletigt Interessenskonflikte

@endmindmap
