@startmindmap
skinparam defaultFontName Courier
title 31102 KE1 1.4 Rahmenbedingungen


+ Rahmenbedingungen
-- Intern 
---_ Orientierung 
----_ Vision
-----_ angestrebte Entwicklung
-----_ sinnstiftend
-----_ motivierend
-----_ handlungsleitend
-----_ integrierend





----_ Mission
-----_ grundlegende UN-Aufgabe
-----_ längerfristig unverändert
-----_ Wertvorstellung

----_ Leitbild
-----_ Konkretisierung Vision+Mission
-----_ muss prägnant und operationalsierbar sein
-----_ Verhaltensmaxime
-----_ Orientierungsrahmen
------_ innen (Umgang mit MA)
------_ aussen (Umgang mit Kunden)
-----_ Entwicklung 
------_ Top Down oder Bottom up
------_ alle Ebenen einbeziehen
------_ ständig reflektieren
-----_ Einhaltung überwachen 




---_ Kultur 
----_ Gesamtheit aller...
-----_ Denkmuster
-----_ Werte
-----_ Verhaltensnormen
----_ ist 
-----_ implizit
-----_ emergent
-----_ nicht greifbar
----_ Wechselwirkung\nUN Mitglieder
-----_ geht aus Interaktion hervor
-----_ und strukturiert Interaktion
----_ Modell nach\n🥼 Schein
-----_ Basis
-----_ Werte
-----_ Artefakte
----_ Einfluss auf
-----_ Prägnanz
-----_ Verbreitung
-----_ Tiefe 
-----_ Attraktion 


---_ Ziele 
----_ Elemente
-----_ Inhalt
-----_ Ausmass
-----_ Zeitlicher Bezug
----_ Anforderung\n an Zielsysteme
-----_ realistisch
-----_ widerspruchsfrei
-----_ vollständig
-----_ anpassbar
-----_ verständlich
-----_ akzeptabel
-----_ motivierend
-----_ kontrollierbar




----_ Beziehungen\nder Zielsysteme
-----_ Interdependenz
------_ komplementär
------_ konkurrenz
------_ neutral 

-----_ Intrumental
-----_ Präferenz


++ Extern 
+++_ Märkte
++++_ Beschaffung
++++_ Kapital
++++_ Arbeiter
++++_ Absatz 

+++_ Umwelt(en)
++++ Märkte in\nden gleichen\nUmwelten\neingebettet
++++_ ökonomisch
++++_ politisch/rechtlich
++++_ sozio/kulturell
++++_ technologisch
++++_ natürlich

+++_ Aufgabenumwelt
++++_ Interkationsperspektiveß
++++_ Wettbewerbsperspektive 


++ Shareholder 
+++_ Aus Eigentümersicht
+++_ Verfahren
++++_ DCF Discoutend Chash Flow 
++++_ EVA Economic Value Added
++++_ CVA Cash Value Added


++ Stakeholder 
+++_ Aus Anspruchshabersicht
+++_ Ressourcen
++++_ Kapital
++++_ Vertrauen
++++_ Informationen
+++_ Kritik: Zu einseitig
@endmindmap
