@startmindmap
skinparam defaultFontName Courier
title 31102 KE1 1.5 Planung und Controlling

+ Unternehmen
++ 5 Managementfunktionen\n🥼 Koontz
+++ ① Planung
++++_ analytische Durchdringung
++++_ erste logische Phase
+++++_ Ziele
+++++_ Vorstrukturierung\nHandlungsalternativen
+++++_ Abschätzung\nErgebnisse
++++_ Planung nicht maximieren\nFlexibilität wahren
++++_ Controlling wichtig\num Planung zu hinterfragen

+++ ② Controlling
++++_ Handlungsebenen
+++++_ Management
++++++_ Entscheiden 1️⃣
++++++_ Durchsetzen
++++++_ Hinterfragen
++++++_ Verantwortung
+++++_ Managementunterstützung
++++++_ Informationsbeschaffung
++++++_ Informationsaufbereitung
++++++_ Informationsbereitstellung 2️⃣
+++++_ Ausführung

+++_ ⓷ Organisation (an anderer Stelle)
+++_ ⓸ Personal (an anderer Stelle)
+++_ ⓹ Führung (an anderer Stelle)

++_ Komplexitätsbewältigung
+++_ 2️⃣ Reflexion\nmithife Informationsbereitstellung
+++_ 1️⃣ Selektion\nals Entscheidung


@endmindmap
